
name: Scan

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: GitRoll Scan
        uses: brenoepics/gitroll-action@v0.1.0
